### ISSUE TITLE
Process Response Card not accepting variable types other than "Contains..."

### ISSUE THREAD

**Issue by hazelarroyo** [bdcheck/Hive-Mechanic-Django#21]
In doing some tests with the Process Response card, I found that changing the type of response ("Begins With...", "Ends With...", "Equals...", "Does not equal...", "Contains...", "Does not contain...") doesn't work. If I save a keyword under anything other than "Contains...", when I refresh the page it reverts back to "Contains...". 

To replicate: 
1. Either create a new pattern on a process response card or edit an existing process response card and classify any keyword variable as any type that is not "Contains..."
2. Save
3. Refresh the page
4. Look back to the Process Response card and you will see that the variable type is now listed as "Contains..."

**Comment by audaciouscode** [comment]
Fixed on workshop.hivemechanic.org.

**Comment by bdcheck** [comment]
M confirms it is now fixed
