### ISSUE TITLE
Receiving emojis causes a session to freeze up until it times out

### ISSUE THREAD

**Issue by mitchellghl** [bdcheck/Hive-Mechanic-Django#22]
Sending a text message to Hive Mechanic while the session is on a process response card causes the session to freeze. You can no longer progress in the session will have to wait until it times out. This happens even if the text message also includes a keyword that the process response is looking for.

To replicate:

1. Start a session and reach a process response card.
2. Send in a text message using any emoji.
3. You will no longer be able to proceed in the session.
4. If you find the session in Django administration, you can see the session is still active but not finished.
5. The session should still eventually end when it automatically times out.

**Comment by audaciouscode** [comment]
Was due to print statements/function calls in card definitions.

Fixed as part of the card code inspector identifying issues with cards and replacing print calls to logging calls.
