### ISSUE TITLE
Possible bug: Initial start text messages are only sometimes processed

### ISSUE THREAD

**Issue by mitchellghl** [bdcheck/Hive-Mechanic-Django#24]
If the start card of a session is a "Send Message" card, which is then followed by a "Process Response" card, the text message sent into Hive Mechanic to begin a session is immediately processed. However, if a Pause is put between the "Send Message" and the "Process Response" cards, the starting text message will not be processed and Hive Mechanic will instead wait until another text message is sent in and process that one instead.

To replicate:
1. Put the first card in the sequence as a "Send Message" card
2. Put the next card in the sequence as a "Process Response" card
3. Save the activity.
4. Send in a text message to the associated number.
5. The text message you sent should be immediately processed after it sends you the first message.

6. Clear any active sessions.
7. Put a 1sec pause between the "Send Message" card and the "Process Response" card
8. Save the activity.
9. Send in a text message to the associate number.
10. After the system sends you the first message, it will NOT process your text message and instead wait until you send in a new message.

**Comment by bdcheck** [comment]
DOne.
