### ISSUE TITLE
HTTP url slug should be distinct to that integration, and be pointed to a game

### ISSUE THREAD

**Issue by bdcheck** [bdcheck/Hive-Mechanic-Django#33]
Currently we only have one integration per server... so Raspis can't talk to different games

(And so that we can see the correct URL for contacting the API from a Raspi)

**Comment by audaciouscode** [comment]
Not needed - I didn't see that the client API key maps the calls to specific games, not the URL and slugs.

So we're already doing this, albeit in a more secure and loggable manner.
